name = "ariady-putra/morbid"
version = "0.2.202310"
license = "Apache-2.0"
description = "An Aiken contract for project 'ariady-putra/morbid'"

[repository]
user = "ariady-putra"
project = "morbid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"

[[dependencies]]
name = "aiken-extra/auxlib"
version = "2.160.202310"
source = "github"

[[dependencies]]
name = "aiken-extra/string_util"
version = "3.160.202310"
source = "github"

[[dependencies]]
name = "aiken-extra/time_util"
version = "5.160.202310"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.160.202310"
source = "github"
