name = "ariady-putra/morbid"
version = "0.2.202307c"
license = "Apache-2.0"
description = "An Aiken contract for project 'ariady-putra/morbid'"

[repository]
user = "ariady-putra"
project = "morbid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.3.0"
source = "github"

[[dependencies]]
name = "aiken-extra/string_util"
version = "2.130.1013-alpha"
source = "github"

[[dependencies]]
name = "aiken-extra/time_util"
version = "5.130.1011-alpha"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.130.1011-alpha"
source = "github"
