name = "ariady-putra/morbid"
version = "0.2.202308g"
license = "Apache-2.0"
description = "An Aiken contract for project 'ariady-putra/morbid'"

[repository]
user = "ariady-putra"
project = "morbid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"

[[dependencies]]
name = "aiken-extra/string_util"
version = "2.150.202308f"
source = "github"

[[dependencies]]
name = "aiken-extra/time_util"
version = "5.150.202308f"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.150.202308f"
source = "github"

[[dependencies]]
name = "aiken-extra/auxlib"
version = "2.150.202308f"
source = "github"
