name = "ariady-putra/morbid"
version = "0.2.202404"
license = "Apache-2.0"
description = "An Aiken contract for project 'ariady-putra/morbid'"

[repository]
user = "ariady-putra"
project = "morbid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"

[[dependencies]]
name = "aiken-extra/auxlib"
version = "2.180.202403"
source = "github"

[[dependencies]]
name = "aiken-extra/string_util"
version = "3.180.202403"
source = "github"

[[dependencies]]
name = "aiken-extra/time_util"
version = "5.180.202403"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "1.180.202403"
source = "github"
