name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.0

      - run: aiken fmt --check
      - run: aiken c -D
      - run: aiken b
